/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as PlanSettingsRouteImport } from './routes/plan-settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ClinicFeesRouteImport } from './routes/clinic-fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ClinicLoginRouteImport } from './routes/clinic.login'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients.$patientId.index'
import { Route as AdminClinicsIndexRouteImport } from './routes/admin.clinics.index'
import { Route as AdminClinicsCreateRouteImport } from './routes/admin.clinics.create'
import { Route as AdminClinicsIdIndexRouteImport } from './routes/admin.clinics.$id.index'
import { Route as PatientsPatientIdPlansPlanIdRouteImport } from './routes/patients.$patientId.plans.$planId'
import { Route as AdminClinicsIdUsersRouteImport } from './routes/admin.clinics.$id.users'
import { Route as AdminClinicsIdEditRouteImport } from './routes/admin.clinics.$id.edit'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSettingsRoute = PlanSettingsRouteImport.update({
  id: '/plan-settings',
  path: '/plan-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicFeesRoute = ClinicFeesRouteImport.update({
  id: '/clinic-fees',
  path: '/clinic-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const ClinicLoginRoute = ClinicLoginRouteImport.update({
  id: '/clinic/login',
  path: '/clinic/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const AdminClinicsIndexRoute = AdminClinicsIndexRouteImport.update({
  id: '/admin/clinics/',
  path: '/admin/clinics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicsCreateRoute = AdminClinicsCreateRouteImport.update({
  id: '/admin/clinics/create',
  path: '/admin/clinics/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicsIdIndexRoute = AdminClinicsIdIndexRouteImport.update({
  id: '/admin/clinics/$id/',
  path: '/admin/clinics/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdPlansPlanIdRoute =
  PatientsPatientIdPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const AdminClinicsIdUsersRoute = AdminClinicsIdUsersRouteImport.update({
  id: '/admin/clinics/$id/users',
  path: '/admin/clinics/$id/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClinicsIdEditRoute = AdminClinicsIdEditRouteImport.update({
  id: '/admin/clinics/$id/edit',
  path: '/admin/clinics/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/documents': typeof DocumentsRoute
  '/overview': typeof OverviewRoute
  '/patients': typeof PatientsRouteWithChildren
  '/plan-settings': typeof PlanSettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/admin/clinics/create': typeof AdminClinicsCreateRoute
  '/admin/clinics/': typeof AdminClinicsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/admin/clinics/$id/edit': typeof AdminClinicsIdEditRoute
  '/admin/clinics/$id/users': typeof AdminClinicsIdUsersRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
  '/admin/clinics/$id/': typeof AdminClinicsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/documents': typeof DocumentsRoute
  '/overview': typeof OverviewRoute
  '/plan-settings': typeof PlanSettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/admin': typeof AdminIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/admin/clinics/create': typeof AdminClinicsCreateRoute
  '/admin/clinics': typeof AdminClinicsIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/admin/clinics/$id/edit': typeof AdminClinicsIdEditRoute
  '/admin/clinics/$id/users': typeof AdminClinicsIdUsersRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
  '/admin/clinics/$id': typeof AdminClinicsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/documents': typeof DocumentsRoute
  '/overview': typeof OverviewRoute
  '/patients': typeof PatientsRouteWithChildren
  '/plan-settings': typeof PlanSettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/clinic/login': typeof ClinicLoginRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/admin/clinics/create': typeof AdminClinicsCreateRoute
  '/admin/clinics/': typeof AdminClinicsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/admin/clinics/$id/edit': typeof AdminClinicsIdEditRoute
  '/admin/clinics/$id/users': typeof AdminClinicsIdUsersRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
  '/admin/clinics/$id/': typeof AdminClinicsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinic-fees'
    | '/documents'
    | '/overview'
    | '/patients'
    | '/plan-settings'
    | '/templates'
    | '/users'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/login'
    | '/patients/$patientId'
    | '/admin/'
    | '/patients/'
    | '/admin/clinics/create'
    | '/admin/clinics/'
    | '/patients/$patientId/'
    | '/admin/clinics/$id/edit'
    | '/admin/clinics/$id/users'
    | '/patients/$patientId/plans/$planId'
    | '/admin/clinics/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinic-fees'
    | '/documents'
    | '/overview'
    | '/plan-settings'
    | '/templates'
    | '/users'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/login'
    | '/admin'
    | '/patients'
    | '/admin/clinics/create'
    | '/admin/clinics'
    | '/patients/$patientId'
    | '/admin/clinics/$id/edit'
    | '/admin/clinics/$id/users'
    | '/patients/$patientId/plans/$planId'
    | '/admin/clinics/$id'
  id:
    | '__root__'
    | '/'
    | '/clinic-fees'
    | '/documents'
    | '/overview'
    | '/patients'
    | '/plan-settings'
    | '/templates'
    | '/users'
    | '/admin/dashboard'
    | '/admin/login'
    | '/clinic/login'
    | '/patients/$patientId'
    | '/admin/'
    | '/patients/'
    | '/admin/clinics/create'
    | '/admin/clinics/'
    | '/patients/$patientId/'
    | '/admin/clinics/$id/edit'
    | '/admin/clinics/$id/users'
    | '/patients/$patientId/plans/$planId'
    | '/admin/clinics/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicFeesRoute: typeof ClinicFeesRoute
  DocumentsRoute: typeof DocumentsRoute
  OverviewRoute: typeof OverviewRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PlanSettingsRoute: typeof PlanSettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ClinicLoginRoute: typeof ClinicLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClinicsCreateRoute: typeof AdminClinicsCreateRoute
  AdminClinicsIndexRoute: typeof AdminClinicsIndexRoute
  AdminClinicsIdEditRoute: typeof AdminClinicsIdEditRoute
  AdminClinicsIdUsersRoute: typeof AdminClinicsIdUsersRoute
  AdminClinicsIdIndexRoute: typeof AdminClinicsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-settings': {
      id: '/plan-settings'
      path: '/plan-settings'
      fullPath: '/plan-settings'
      preLoaderRoute: typeof PlanSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-fees': {
      id: '/clinic-fees'
      path: '/clinic-fees'
      fullPath: '/clinic-fees'
      preLoaderRoute: typeof ClinicFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/clinic/login': {
      id: '/clinic/login'
      path: '/clinic/login'
      fullPath: '/clinic/login'
      preLoaderRoute: typeof ClinicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/admin/clinics/': {
      id: '/admin/clinics/'
      path: '/admin/clinics'
      fullPath: '/admin/clinics/'
      preLoaderRoute: typeof AdminClinicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinics/create': {
      id: '/admin/clinics/create'
      path: '/admin/clinics/create'
      fullPath: '/admin/clinics/create'
      preLoaderRoute: typeof AdminClinicsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinics/$id/': {
      id: '/admin/clinics/$id/'
      path: '/admin/clinics/$id'
      fullPath: '/admin/clinics/$id/'
      preLoaderRoute: typeof AdminClinicsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/plans/$planId': {
      id: '/patients/$patientId/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/patients/$patientId/plans/$planId'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/admin/clinics/$id/users': {
      id: '/admin/clinics/$id/users'
      path: '/admin/clinics/$id/users'
      fullPath: '/admin/clinics/$id/users'
      preLoaderRoute: typeof AdminClinicsIdUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clinics/$id/edit': {
      id: '/admin/clinics/$id/edit'
      path: '/admin/clinics/$id/edit'
      fullPath: '/admin/clinics/$id/edit'
      preLoaderRoute: typeof AdminClinicsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdPlansPlanIdRoute: typeof PatientsPatientIdPlansPlanIdRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdPlansPlanIdRoute: PatientsPatientIdPlansPlanIdRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicFeesRoute: ClinicFeesRoute,
  DocumentsRoute: DocumentsRoute,
  OverviewRoute: OverviewRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PlanSettingsRoute: PlanSettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ClinicLoginRoute: ClinicLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClinicsCreateRoute: AdminClinicsCreateRoute,
  AdminClinicsIndexRoute: AdminClinicsIndexRoute,
  AdminClinicsIdEditRoute: AdminClinicsIdEditRoute,
  AdminClinicsIdUsersRoute: AdminClinicsIdUsersRoute,
  AdminClinicsIdIndexRoute: AdminClinicsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
