/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as ClinicFeesRouteImport } from './routes/clinic-fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients.$patientId.index'
import { Route as PatientsPatientIdPlansPlanIdRouteImport } from './routes/patients.$patientId.plans.$planId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicFeesRoute = ClinicFeesRouteImport.update({
  id: '/clinic-fees',
  path: '/clinic-fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const PatientsPatientIdPlansPlanIdRoute =
  PatientsPatientIdPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/users': typeof UsersRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/users': typeof UsersRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinic-fees': typeof ClinicFeesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/users': typeof UsersRoute
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
  '/patients/$patientId/plans/$planId': typeof PatientsPatientIdPlansPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clinic-fees'
    | '/patients'
    | '/users'
    | '/patients/$patientId'
    | '/patients/'
    | '/patients/$patientId/'
    | '/patients/$patientId/plans/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clinic-fees'
    | '/users'
    | '/patients'
    | '/patients/$patientId'
    | '/patients/$patientId/plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/clinic-fees'
    | '/patients'
    | '/users'
    | '/patients/$patientId'
    | '/patients/'
    | '/patients/$patientId/'
    | '/patients/$patientId/plans/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicFeesRoute: typeof ClinicFeesRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-fees': {
      id: '/clinic-fees'
      path: '/clinic-fees'
      fullPath: '/clinic-fees'
      preLoaderRoute: typeof ClinicFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/plans/$planId': {
      id: '/patients/$patientId/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/patients/$patientId/plans/$planId'
      preLoaderRoute: typeof PatientsPatientIdPlansPlanIdRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
  }
}

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
  PatientsPatientIdPlansPlanIdRoute: typeof PatientsPatientIdPlansPlanIdRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
  PatientsPatientIdPlansPlanIdRoute: PatientsPatientIdPlansPlanIdRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicFeesRoute: ClinicFeesRoute,
  PatientsRoute: PatientsRouteWithChildren,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
